# Generated by Django 3.2.6 on 2021-09-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
